export type PolicyKind = 'conduct' | 'rules';

type PolicySection = { title: string; paragraphs?: string[]; bullets?: string[] };
export type PolicyPageContent = { eyebrow: string; title: string; intro: string; sections: PolicySection[]; back: string };

export const policyCopy: Record<'en' | 'es' | 'fr' | 'de', Record<PolicyKind, PolicyPageContent>> = {
  en: {
    conduct: {
      eyebrow: 'Community standard', title: 'Code of conduct', back: 'Back to home',
      intro: 'MPOTA exists to make amateur radio more visible, accessible, and welcoming in the municipal parks around us. Everyone who uses the programme helps shape that experience.',
      sections: [
        { title: 'Participants will', bullets: ['Follow the MPOTA rules, their amateur-radio licence conditions, and the laws and regulations of the place where they operate.', 'Treat municipal staff, members of the public, other operators, volunteers, and programme administrators with respect.', 'Operate courteously, keep contacts and uploaded logs honest, and correct mistakes when they are found.', 'Respect park access guidance, opening hours, protected areas, noise limits, and the instructions of local officials.', 'Keep programme discussions and reports relevant, constructive, and respectful.'] },
        { title: 'Participants will not', bullets: ['Harass, threaten, discriminate against, abuse, or deliberately intimidate another person.', 'Claim contacts that were not made, manipulate records, impersonate another operator, or misuse MPOTA awards or references.', 'Trespass, obstruct normal public use of a park, damage property, or create an avoidable safety risk.', 'Use MPOTA channels for unlawful activity, spam, unsolicited advertising, copyright infringement, or malicious content.', 'Attempt to bypass access controls, disrupt the service, scrape it irresponsibly, or access another user’s data.'] },
        { title: 'Moderation and reports', paragraphs: ['MPOTA administrators may review activity, request clarification, restrict access, retire invalid records, or suspend an account when this standard or the programme rules are breached. Serious or repeated violations may result in permanent removal of access or data associated with the account, subject to applicable law and record-retention needs.', 'Please report concerns through the programme’s designated administration channel with enough factual detail to allow a fair review. Reports and moderation decisions will be handled discreetly.'] }
      ]
    },
    rules: {
      eyebrow: 'How the programme works', title: 'MPOTA rules', back: 'Back to home',
      intro: 'These rules define how municipal-park activations, contacts, submissions, and awards are counted. Local law, licence conditions, and the instructions of park authorities always take priority.',
      sections: [
        { title: 'Key definitions', bullets: ['Activator: a licensed amateur operator transmitting from an active MPOTA entity.', 'Hunter: an operator who makes a valid contact with an activator. The hunter may be anywhere permitted by their licence and local law.', 'Activation: an activator’s operating activity at one MPOTA entity on one UTC calendar day.'] },
        { title: 'Activations and attempts', bullets: ['A valid activation requires at least 10 valid QSOs from the same active entity by the same activator during one UTC day.', 'An activation with fewer than 10 valid QSOs remains visible as Failed so valid hunter contacts are preserved, but it gives no activator credit and does not qualify activator awards.', 'Upload unsuccessful logs when possible: hunters can still receive credit from valid contacts even when the activation threshold is not reached.', 'Multiple logs for the same activator, entity, and UTC day are evaluated together as one activation.'] },
        { title: 'Eligible QSOs', bullets: ['Use any legal amateur band and mode permitted by the operators’ licences and applicable band plans.', 'Each contact must be a genuine two-way contact involving direct action by both operators. Fully automated contacts and relays are not valid.', 'An operator may not claim a contact with their own station or callsign. Future-dated QSOs are not valid.', 'A hunter callsign does not need to be registered in MPOTA for the QSO to be valid.'] },
        { title: 'Location, access, and safety', bullets: ['The activator and station equipment must be within the publicly accessible area of the active MPOTA municipal park, unless a lawful permit provides otherwise.', 'Follow municipal access rules, opening times, restrictions, event controls, and instructions from park staff. Do not trespass or interfere with other park users.', 'A retired entity remains in historical listings, but no new QSOs may be accepted while it is inactive.'] },
        { title: 'MPOTA eligibility and the POTA boundary', paragraphs: ['MPOTA is complementary to Parks on the Air and is not a competing programme. A park already included in POTA is not eligible for MPOTA. MPOTA is intended for municipally managed parks that are outside POTA and accessible to the public.', 'A proposed entity should have a credible municipal source or other reliable public information. Administrators may request evidence, reject duplicates, or retire an entry when its status or eligibility changes.'] },
        { title: 'Logging and validation', bullets: ['ADIF uploads must identify the selected MPOTA entity and include enough information to validate the contact, including callsign, UTC date/time, band, and mode.', 'Duplicate QSOs, repeated hunter callsigns within one uploaded ADIF file, and more than one valid contact with the same hunter by the same activator at the same entity on the same UTC day are rejected.', 'Submit logs promptly and keep the original log available in case an administrator needs clarification. MPOTA retains rejected records with their reason for transparency.', 'Awards are calculated from validated data. Hunter credit is independent of the 10-QSO activator threshold.'] },
        { title: 'Submissions and decisions', paragraphs: ['Registered users may propose a municipal park on the map. Proposals are pending until an authorised regional or global administrator reviews them. Global administrators may approve, reject, or retire entities; parks are retired rather than deleted so historical QSOs remain meaningful.', 'If these rules conflict with a specific local law, licence condition, or official municipal instruction, that higher authority prevails.'] },
        { title: 'Reporting a concern', paragraphs: ['If you find an incorrect entity, access problem, duplicate, invalid log, or possible rule violation, submit a factual report through the programme administration channel. Include the reference, date, and supporting information where available.'] }
      ]
    }
  },
  es: {
    conduct: {
      eyebrow: 'Normas de la comunidad', title: 'Código de conducta', back: 'Volver al inicio',
      intro: 'MPOTA existe para hacer la radioafición más visible, accesible y acogedora en los parques municipales que nos rodean. Todas las personas que usan el programa ayudan a crear esa experiencia.',
      sections: [
        { title: 'Los participantes deben', bullets: ['Cumplir las reglas de MPOTA, las condiciones de su licencia y las leyes del lugar donde operan.', 'Tratar con respeto al personal municipal, al público, a otros operadores, voluntarios y administradores.', 'Operar con cortesía, mantener honestos los contactos y registros enviados y corregir los errores detectados.', 'Respetar las indicaciones de acceso, horarios, zonas protegidas, límites de ruido y las instrucciones de las autoridades.', 'Mantener las conversaciones del programa relevantes, constructivas y respetuosas.'] },
        { title: 'Los participantes no deben', bullets: ['Acosar, amenazar, discriminar, insultar o intimidar deliberadamente a otra persona.', 'Declarar contactos no realizados, manipular registros, suplantar a otro operador o utilizar indebidamente premios o referencias.', 'Entrar sin permiso, obstaculizar el uso normal del parque, dañar bienes o crear riesgos evitables.', 'Usar los canales de MPOTA para actividades ilegales, spam, publicidad no solicitada, infracciones de copyright o contenido malicioso.', 'Intentar eludir controles de acceso, interrumpir el servicio o acceder a los datos de otra persona.'] },
        { title: 'Moderación y avisos', paragraphs: ['Los administradores pueden revisar la actividad, pedir aclaraciones, limitar el acceso, retirar registros inválidos o suspender cuentas. Las infracciones graves o repetidas pueden causar la pérdida permanente del acceso, conforme a la ley y a las necesidades de conservación de registros.', 'Informa de los problemas mediante el canal de administración indicado, aportando datos objetivos para permitir una revisión justa. Los avisos y decisiones se tratarán con discreción.'] }
      ]
    },
    rules: {
      eyebrow: 'Cómo funciona el programa', title: 'Reglas de MPOTA', back: 'Volver al inicio',
      intro: 'Estas reglas definen cómo se cuentan las activaciones, contactos, propuestas y premios en parques municipales. La legislación, la licencia y las instrucciones de las autoridades del parque siempre tienen prioridad.',
      sections: [
        { title: 'Definiciones', bullets: ['Activador: operador de radioafición con licencia que transmite desde una entidad MPOTA activa.', 'Cazador: operador que realiza un contacto válido con un activador. Puede estar en cualquier lugar permitido por su licencia y la ley.', 'Activación: actividad de un activador en una entidad MPOTA durante un día UTC.'] },
        { title: 'Activaciones e intentos', bullets: ['Una activación válida necesita al menos 10 QSOs válidos de la misma entidad, realizados por el mismo activador durante un día UTC.', 'Una activación con menos de 10 QSOs válidos sigue apareciendo como Fallida para conservar los contactos de los cazadores, pero no da crédito al activador ni permite premios de activador.', 'Siempre que sea posible, envía también los logs fallidos: los cazadores pueden recibir crédito por contactos válidos.', 'Varios logs del mismo activador, entidad y día UTC se evalúan como una sola activación.'] },
        { title: 'QSOs válidos', bullets: ['Se puede utilizar cualquier banda y modo legal permitido por las licencias y planes de banda.', 'Cada contacto debe ser bidireccional y requerir acción directa de ambos operadores. No se permiten contactos totalmente automáticos ni repetidores/relés.', 'No se puede declarar un contacto con la propia estación o indicativo. Los QSOs futuros no son válidos.', 'El indicativo del cazador no tiene que estar registrado en MPOTA para que el QSO sea válido.'] },
        { title: 'Ubicación, acceso y seguridad', bullets: ['El activador y el equipo deben estar dentro de la zona pública accesible del parque municipal MPOTA activo, salvo permiso legal.', 'Respeta las normas municipales, horarios, restricciones, eventos y al personal del parque. No entres sin permiso ni molestes a otros usuarios.', 'Una entidad retirada permanece en los listados históricos, pero no acepta nuevos QSOs mientras esté inactiva.'] },
        { title: 'Elegibilidad MPOTA y límite con POTA', paragraphs: ['MPOTA complementa a Parks on the Air y no compite con él. Un parque que ya está incluido en POTA no es elegible para MPOTA. MPOTA está destinado a parques gestionados por municipios, fuera de POTA y accesibles al público.', 'Las propuestas deben aportar una fuente municipal creíble u otra información pública fiable. Los administradores pueden pedir pruebas, rechazar duplicados o retirar una entrada si cambia su elegibilidad.'] },
        { title: 'Logs y validación', bullets: ['Los uploads ADIF deben identificar la entidad MPOTA seleccionada e incluir indicativo, fecha/hora UTC, banda y modo.', 'Se rechazan QSOs duplicados, indicativos de cazador repetidos dentro del mismo ADIF y más de un contacto válido con el mismo cazador, activador y entidad en el mismo día UTC.', 'Envía los logs pronto y conserva el original. MPOTA conserva los registros rechazados y el motivo para facilitar la transparencia.', 'Los premios se calculan con datos validados. El crédito del cazador no depende del umbral de 10 QSOs.'] },
        { title: 'Propuestas y decisiones', paragraphs: ['Las personas registradas pueden proponer parques desde el mapa. Una propuesta queda pendiente hasta que la revise un administrador autorizado. Los administradores globales pueden aprobar, rechazar o retirar entidades; los parques se retiran, no se borran, para conservar el historial.', 'Si estas reglas contradicen una ley, licencia o instrucción oficial, prevalece esa autoridad superior.'] },
        { title: 'Comunicar un problema', paragraphs: ['Comunica entidades incorrectas, problemas de acceso, duplicados, logs inválidos o posibles infracciones mediante el canal de administración, incluyendo referencia, fecha y pruebas cuando existan.'] }
      ]
    }
  },
  fr: {
    conduct: {
      eyebrow: 'Règles de la communauté', title: 'Code de conduite', back: 'Retour à l’accueil',
      intro: 'MPOTA veut rendre la radio amateur plus visible, accessible et accueillante dans les parcs municipaux qui nous entourent. Chaque participant contribue à cette expérience.',
      sections: [
        { title: 'Les participants doivent', bullets: ['Respecter les règles MPOTA, les conditions de leur licence et les lois du lieu d’exploitation.', 'Traiter avec respect le personnel municipal, le public, les opérateurs, les bénévoles et les administrateurs.', 'Opérer avec courtoisie, conserver des contacts et des logs sincères et corriger les erreurs découvertes.', 'Respecter les accès, horaires, zones protégées, limites sonores et consignes des autorités locales.', 'Garder les échanges du programme pertinents, constructifs et respectueux.'] },
        { title: 'Les participants ne doivent pas', bullets: ['Harceler, menacer, discriminer, insulter ou intimider volontairement une autre personne.', 'Déclarer des contacts non réalisés, falsifier des logs, usurper un indicatif ou détourner les récompenses.', 'Entrer sans autorisation, gêner le public, dégrader un bien ou créer un risque évitable.', 'Utiliser les canaux MPOTA pour des activités illégales, du spam, de la publicité non sollicitée ou du contenu malveillant.', 'Contourner les contrôles d’accès, perturber le service ou accéder aux données d’un autre utilisateur.'] },
        { title: 'Modération et signalements', paragraphs: ['Les administrateurs peuvent examiner l’activité, demander des précisions, limiter l’accès, retirer des données invalides ou suspendre un compte. Les violations graves ou répétées peuvent entraîner une exclusion permanente, selon la loi et les besoins de conservation.', 'Signalez les problèmes par le canal d’administration prévu, avec des faits permettant un examen équitable. Les signalements et décisions sont traités avec discrétion.'] }
      ]
    },
    rules: {
      eyebrow: 'Fonctionnement du programme', title: 'Règles MPOTA', back: 'Retour à l’accueil',
      intro: 'Ces règles définissent le calcul des activations, contacts, propositions et récompenses dans les parcs municipaux. La loi, la licence et les consignes du parc restent prioritaires.',
      sections: [
        { title: 'Définitions', bullets: ['Activateur : opérateur radioamateur autorisé à émettre depuis une entité MPOTA active.', 'Chasseur : opérateur qui établit un contact valide avec un activateur, depuis tout lieu autorisé.', 'Activation : activité d’un activateur dans une entité MPOTA pendant un jour UTC.'] },
        { title: 'Activations et tentatives', bullets: ['Une activation valide exige au moins 10 QSOs valides dans la même entité, par le même activateur et le même jour UTC.', 'Une activation de moins de 10 QSOs valides reste affichée comme Échouée afin de préserver le crédit des chasseurs, mais ne donne aucun crédit à l’activateur et ne qualifie pas ses récompenses.', 'Envoyez aussi les logs incomplets lorsque possible : les chasseurs peuvent recevoir le crédit de leurs contacts valides.', 'Les logs du même activateur, de la même entité et du même jour UTC sont regroupés en une seule activation.'] },
        { title: 'QSOs admissibles', bullets: ['Toutes les bandes et tous les modes légaux autorisés par les licences peuvent être utilisés.', 'Chaque contact doit être bidirectionnel et effectué directement par les deux opérateurs. Les contacts entièrement automatisés et les relais sont interdits.', 'Il est interdit de valider un contact avec sa propre station ou son propre indicatif. Les QSOs futurs sont invalides.', 'Un indicatif chasseur ne doit pas être enregistré dans MPOTA pour qu’un QSO soit valide.'] },
        { title: 'Lieu, accès et sécurité', bullets: ['L’activateur et son matériel doivent se trouver dans la partie publique accessible du parc municipal MPOTA actif, sauf autorisation légale.', 'Respectez les règles municipales, horaires, restrictions, événements et consignes du personnel. Ne faites pas d’intrusion et ne gênez pas le public.', 'Une entité retirée reste dans l’historique, mais aucun nouveau QSO n’est accepté pendant son inactivation.'] },
        { title: 'Éligibilité MPOTA et limite avec POTA', paragraphs: ['MPOTA complète Parks on the Air et ne le concurrence pas. Un parc déjà inscrit dans POTA n’est pas éligible à MPOTA. MPOTA concerne les parcs gérés par une municipalité, hors POTA et accessibles au public.', 'Une proposition doit s’appuyer sur une source municipale crédible ou une information publique fiable. Les administrateurs peuvent demander des preuves, refuser les doublons ou retirer une entité devenue inéligible.'] },
        { title: 'Logs et validation', bullets: ['Les fichiers ADIF doivent identifier l’entité MPOTA choisie et fournir indicatif, date/heure UTC, bande et mode.', 'Les doublons, les indicatifs chasseurs répétés dans un même ADIF et plusieurs contacts valides avec le même chasseur, activateur et entité le même jour UTC sont rejetés.', 'Envoyez les logs rapidement et conservez l’original. Les enregistrements rejetés et leur motif sont conservés pour la transparence.', 'Les récompenses utilisent les données validées. Le crédit chasseur est indépendant du seuil de 10 QSOs.'] },
        { title: 'Propositions et décisions', paragraphs: ['Les utilisateurs inscrits peuvent proposer un parc depuis la carte. La proposition reste en attente jusqu’à sa revue par un administrateur habilité. Les administrateurs globaux peuvent approuver, refuser ou retirer une entité ; les parcs sont retirés, pas supprimés, pour préserver l’historique.', 'En cas de conflit avec une loi, une licence ou une consigne officielle, cette autorité supérieure prévaut.'] },
        { title: 'Signaler un problème', paragraphs: ['Signalez une entité incorrecte, un problème d’accès, un doublon, un log invalide ou une infraction présumée via le canal d’administration, avec la référence, la date et les éléments utiles.'] }
      ]
    }
  },
  de: {
    conduct: {
      eyebrow: 'Gemeinschaftsstandard', title: 'Verhaltenskodex', back: 'Zur Startseite',
      intro: 'MPOTA soll den Amateurfunk in den kommunalen Parks unserer Umgebung sichtbarer, zugänglicher und freundlicher machen. Alle Teilnehmenden prägen diese Erfahrung mit.',
      sections: [
        { title: 'Teilnehmende müssen', bullets: ['Die MPOTA-Regeln, ihre Lizenzbedingungen und die Gesetze am Betriebsort einhalten.', 'Gemeindemitarbeitende, Öffentlichkeit, andere Funkamateure, Freiwillige und Administratoren respektvoll behandeln.', 'Höflich funken, Kontakte und Logs wahrheitsgemäß führen und erkannte Fehler korrigieren.', 'Zugangshinweise, Öffnungszeiten, Schutzbereiche, Lärmgrenzen und Anweisungen lokaler Behörden beachten.', 'Programmdiskussionen sachlich, konstruktiv und respektvoll führen.'] },
        { title: 'Teilnehmende dürfen nicht', bullets: ['Andere Personen belästigen, bedrohen, diskriminieren, beleidigen oder absichtlich einschüchtern.', 'Nicht geführte Kontakte behaupten, Logs manipulieren, fremde Rufzeichen vortäuschen oder Auszeichnungen missbrauchen.', 'Unbefugt betreten, die öffentliche Nutzung behindern, Eigentum beschädigen oder vermeidbare Risiken verursachen.', 'MPOTA-Kanäle für illegale Aktivitäten, Spam, unerwünschte Werbung, Copyright-Verletzungen oder Schadsoftware nutzen.', 'Zugangskontrollen umgehen, den Dienst stören oder auf Daten anderer Nutzer zugreifen.'] },
        { title: 'Moderation und Meldungen', paragraphs: ['Administratoren können Aktivitäten prüfen, Nachweise anfordern, Zugänge beschränken, ungültige Daten entfernen oder Konten sperren. Schwere oder wiederholte Verstöße können unter Beachtung von Recht und Aufbewahrungspflichten zum dauerhaften Ausschluss führen.', 'Melde Probleme über den vorgesehenen Administrationskanal und füge sachliche Angaben bei, damit eine faire Prüfung möglich ist. Meldungen und Entscheidungen werden vertraulich behandelt.'] }
      ]
    },
    rules: {
      eyebrow: 'So funktioniert das Programm', title: 'MPOTA-Regeln', back: 'Zur Startseite',
      intro: 'Diese Regeln legen fest, wie Aktivierungen, QSOs, Vorschläge und Auszeichnungen in kommunalen Parks zählen. Gesetze, Lizenzbedingungen und Anweisungen der Parkverwaltung haben immer Vorrang.',
      sections: [
        { title: 'Definitionen', bullets: ['Aktivierer: lizenzierter Funkamateur, der aus einer aktiven MPOTA-Entität sendet.', 'Jäger: Funkamateur, der einen gültigen Kontakt mit einem Aktivierer herstellt. Der Standort muss für ihn rechtmäßig sein.', 'Aktivierung: die Aktivität eines Aktivierers in einer MPOTA-Entität an einem UTC-Kalendertag.'] },
        { title: 'Aktivierungen und Versuche', bullets: ['Eine gültige Aktivierung erfordert mindestens 10 gültige QSOs aus derselben Entität durch denselben Aktivierer an einem UTC-Tag.', 'Eine Aktivierung mit weniger als 10 gültigen QSOs bleibt als Fehlgeschlagen sichtbar, damit Jäger ihre gültigen Kontakte behalten; sie bringt dem Aktivierer jedoch keinen Kredit und qualifiziert keine Aktivierer-Auszeichnung.', 'Lade auch unvollständige Logs möglichst hoch: Jäger können für gültige Kontakte weiterhin Kredit erhalten.', 'Mehrere Logs desselben Aktivierers, derselben Entität und desselben UTC-Tages werden zu einer Aktivierung zusammengefasst.'] },
        { title: 'Gültige QSOs', bullets: ['Alle legalen Bänder und Betriebsarten entsprechend Lizenz und Bandplan sind zulässig.', 'Jeder Kontakt muss ein echter, direkter Zweiwegkontakt beider Funkamateure sein. Vollautomatische Kontakte und Relais sind nicht gültig.', 'Kontakte mit der eigenen Station oder dem eigenen Rufzeichen dürfen nicht angerechnet werden. Zukünftige QSOs sind ungültig.', 'Das Rufzeichen eines Jägers muss nicht im MPOTA-System registriert sein.'] },
        { title: 'Ort, Zugang und Sicherheit', bullets: ['Aktivierer und Ausrüstung müssen sich im öffentlich zugänglichen Bereich des aktiven kommunalen MPOTA-Parks befinden, außer eine rechtmäßige Genehmigung erlaubt etwas anderes.', 'Beachte kommunale Regeln, Öffnungszeiten, Einschränkungen, Veranstaltungen und Anweisungen des Parkpersonals. Kein Hausfriedensbruch und keine Behinderung der Öffentlichkeit.', 'Eine stillgelegte Entität bleibt in historischen Listen, akzeptiert aber keine neuen QSOs, solange sie inaktiv ist.'] },
        { title: 'MPOTA-Eignung und Abgrenzung zu POTA', paragraphs: ['MPOTA ergänzt Parks on the Air und tritt nicht in Konkurrenz dazu. Ein Park, der bereits in POTA enthalten ist, ist nicht für MPOTA zugelassen. MPOTA richtet sich an kommunal verwaltete, öffentlich zugängliche Parks außerhalb von POTA.', 'Ein Vorschlag sollte eine glaubwürdige kommunale Quelle oder andere verlässliche öffentliche Informationen enthalten. Administratoren können Nachweise anfordern, Duplikate ablehnen oder eine Entität bei geänderter Eignung stilllegen.'] },
        { title: 'Logs und Prüfung', bullets: ['ADIF-Dateien müssen die ausgewählte MPOTA-Entität nennen und Rufzeichen, UTC-Datum/-Zeit, Band und Betriebsart enthalten.', 'Doppelte QSOs, wiederholte Jäger-Rufzeichen in derselben ADIF-Datei sowie mehrere gültige Kontakte mit demselben Jäger durch denselben Aktivierer in derselben Entität am selben UTC-Tag werden abgelehnt.', 'Sende Logs zeitnah und bewahre das Original auf. Abgelehnte Datensätze und der Grund bleiben zur Nachvollziehbarkeit erhalten.', 'Auszeichnungen werden aus geprüften Daten berechnet. Jägerkredit ist unabhängig von der 10-QSO-Schwelle.'] },
        { title: 'Vorschläge und Entscheidungen', paragraphs: ['Registrierte Nutzer können Parks über die Karte vorschlagen. Ein Vorschlag bleibt offen, bis ein zuständiger Administrator ihn geprüft hat. Globale Administratoren können Entitäten genehmigen, ablehnen oder stilllegen; Parks werden stillgelegt und nicht gelöscht, damit die Historie erhalten bleibt.', 'Bei Widerspruch zu Gesetz, Lizenzbedingung oder offizieller Anweisung gilt die höherrangige Vorgabe.'] },
        { title: 'Problem melden', paragraphs: ['Melde falsche Entitäten, Zugangsprobleme, Duplikate, ungültige Logs oder vermutete Regelverstöße über den Administrationskanal. Gib nach Möglichkeit Referenz, Datum und Belege an.'] }
      ]
    }
  }
};
