apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mpota-test
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/ea7klk/mpota.git
    targetRevision: main
    path: deploy/k8s/overlays/test
  destination:
    server: https://kubernetes.default.svc
    namespace: mpota-test
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
